=== artemyeve/OldCards/data/cards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/oldcards"
        xmlns:tns="http://www.example.com/oldcards"
        elementFormDefault="qualified">
    <element name="card" type="tns:descriptionOfCard"></element>
    <element name="old_cards">
        <complexType>
            <sequence>
                <element ref="tns:card"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="descriptionOfCard">
        <complexContent>
            <extension base="tns:InformationAboutCard">
                <attribute name="cardID" type="tns:CardID" use="required"/>
                <attribute name="author" use="optional"/>
                <attribute name="send" type="boolean" use="required"/>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="CardID">
        <restriction base="ID">
            <pattern value="[a-zA-Z0-9]{4,9}"/>
        </restriction>
    </simpleType>
    <complexType name="InformationAboutCard">
        <sequence>
            <element name="thema" default="people">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="people"/>
                        <enumeration value="sport"/>
                        <enumeration value="architecture"/>
                        <enumeration value="cityscape"/>
                        <enumeration value="animal"/>
                        <enumeration value="nature"/>
                        <enumeration value="religion"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="country" type="string"/>
            <element name="year" type="positiveInteger"/>
            <element name="valuable" default="historical">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="historical"/>
                        <enumeration value="collection"/>
                        <enumeration value="thematic"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="type" default="greeting">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="greeting"/>
                        <enumeration value="advertising"/>
                        <enumeration value="usual"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
</schema>

=== artemyeve/OldCards/data/cards.xml
<?xml version="1.0" encoding="UTF-8"?>
<old_cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.example.com/oldcards"
           xsi:schemaLocation="http://www.example.com/oldcards cards.xsd">
    <card cardID="fjiel21" send="true">
        <thema>people</thema>
        <country>America</country>
        <year>1935</year>
        <valuable>historical</valuable>
        <type>usual</type>
    </card>
    <card cardID="frekgke" send="true" author="Sychou">
        <thema>cityscape</thema>
        <country>Belarus</country>
        <year>1991</year>
        <valuable>historical</valuable>
        <type>usual</type>
    </card>
    <card cardID="ferg124" send="false">
        <thema>animal</thema>
        <country>America</country>
        <year>1938</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="ferf421" send="false" author="Bogdevich">
        <thema>nature</thema>
        <country>Belarus</country>
        <year>1992</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="tru124" send="false">
        <thema>sport</thema>
        <country>America</country>
        <year>1922</year>
        <valuable>collection</valuable>
        <type>advertising</type>
    </card>
    <card cardID="fehj421" send="false" author="Bogdevich">
        <thema>architecture</thema>
        <country>Belarus</country>
        <year>1991</year>
        <valuable>collection</valuable>
        <type>advertising</type>
    </card>
    <card cardID="feww24" send="false">
        <thema>religion</thema>
        <country>Poland</country>
        <year>1944</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="fezv1" send="false" author="Bogdevich">
        <thema>sport</thema>
        <country>Belarus</country>
        <year>1991</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="fsght24" send="false">
        <thema>people</thema>
        <country>Spain</country>
        <year>1915</year>
        <valuable>collection</valuable>
        <type>usual</type>
    </card>
    <card cardID="fsef21" send="false" author="Bogdevich">
        <thema>architecture</thema>
        <country>Belarus</country>
        <year>1993</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="fehjm24" send="false">
        <thema>sport</thema>
        <country>America</country>
        <year>1939</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="fbgf1" send="false">
        <thema>people</thema>
        <country>Finland</country>
        <year>1915</year>
        <valuable>historical</valuable>
        <type>greeting</type>
    </card>
    <card cardID="fnhf24" send="false">
        <thema>architecture</thema>
        <country>America</country>
        <year>1933</year>
        <valuable>historical</valuable>
        <type>greeting</type>
    </card>
    <card cardID="zvx21" send="false" author="Bogdevich">
        <thema>religion</thema>
        <country>Belarus</country>
        <year>1925</year>
        <valuable>collection</valuable>
        <type>usual</type>
    </card>
    <card cardID="fnhg4" send="false">
        <thema>sport</thema>
        <country>America</country>
        <year>1951</year>
        <valuable>collection</valuable>
        <type>usual</type>
    </card>
    <card cardID="fehg21" send="false">
        <thema>people</thema>
        <country>Sweden</country>
        <year>1991</year>
        <valuable>historical</valuable>
        <type>greeting</type>
    </card>
    <card cardID="fnhngh24" send="false">
        <thema>architecture</thema>
        <country>Egypt</country>
        <year>1900</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="nhggf421" send="false" author="Bogdevich">
        <thema>people</thema>
        <country>Belarus</country>
        <year>1981</year>
        <valuable>collection</valuable>
        <type>greeting</type>
    </card>
    <card cardID="jhmhj124" send="false">
        <thema>sport</thema>
        <country>America</country>
        <year>1912</year>
        <valuable>collection</valuable>
        <type>advertising</type>
    </card>
    <card cardID="fgrf421" send="false" author="Bogdevich">
        <thema>architecture</thema>
        <country>Belarus</country>
        <year>1997</year>
        <valuable>collection</valuable>
        <type>advertising</type>
    </card>
</old_cards>
